### PR TITLE
Allows Customizing Project Location on Gradle Wrapper

### PR DESCRIPTION
**Pull request by andreban**
@JudahGabriel drafted this to enable customizing the Gradle Wrapper.

### CODE REVIEW

**Comment by JudahGabriel** [comment]
OK, I think the issue is we should instead be [setting the current directory of the node child process](https://stackoverflow.com/a/18898027/536). 

I think the final code would look like this:

```js
class GradleWrapper {
  constructor(process, androidSdkTools, gradleDirectory) {
    this.process = process;
    this.gradleDirectory = gradleDirectory;
    this.androidSdkTools = androidSdkTools;
    if (process.platform === 'win32') {
      this.gradleCmd = 'gradlew.bat';
    } else {
      this.gradleCmd = './gradlew';
    }
  }

  async assembleRelease() {
    const env = this.androidSdkTools.getEnv();
    await exec(`${this.gradleCmd} assembleRelease --stacktrace`, {
      env: env,
      cwd: gradleDirectory
   });
  }
```

I'll test this first and follow up shortly with the results.

**Comment by JudahGabriel** [comment]
The above code seems to work - instead of appending the gradleDirectory to gradleCmd, just use the cwd option:

```js
await exec(`${this.gradleCmd} assembleRelease --stacktrace`, {
   env: androidSdkTools.getEnv(),
   cwd: gradleDirectory // set the current directory for the child process
});
```

**Comment by andreban** [comment]
Ha! Sounds like I was overcomplicating things. Thanks for checking this out. I'll update the PR.

**Comment by andreban** [comment]
@JudahGabriel does this sound good?

**Pull request merged**
